PHP/Laravel/Projekti/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
Route::get('/', [
    'uses' => '\teht\Http\Controllers\HomeController@index',
    'as'   => 'index'
]);

Route::get('/auth/register', [
    'uses' => '\teht\Http\Controllers\AuthController@getRegister',
    'as'   => 'auth.register',
    'middleware' => ['guest']
]);
 
Route::post('/auth/register', [
    'uses' => '\teht\Http\Controllers\AuthController@postRegister',
    'middleware' => ['guest']
]);
 
Route::get('/auth/signin', [
    'uses' => '\teht\Http\Controllers\AuthController@getLogin',
    'as'   => 'auth.login',
    'middleware' => ['guest']
]);
 
Route::post('/auth/signin', [
    'uses' => '\teht\Http\Controllers\AuthController@postLogIn',
    'middleware' => ['guest']
]);
 
Route::get('/logout', [
    'uses' => '\teht\Http\Controllers\AuthController@logOut',
    'as'   => 'auth.logout'
]);

Route::resource('projects', 'ProjectController');

Route::post('projects/{projects}/tasks', [
    'uses' => '\teht\Http\Controllers\ProjectTasksController@postNewTask',
    'as' => 'projects.tasks.create'
]);

Route::get('projects/{projects}/tasks/{tasks}/edit', [
    'uses' => '\teht\Http\Controllers\ProjectTasksController@getOneProjectTask',
    'as' => 'projects.tasks'
]);
 
Route::put('projects/{projects}/tasks/{tasks}', [
    'uses' => '\teht\Http\Controllers\ProjectTasksController@updateOneProjectTask',
]);

Route::delete('projects/{projects}/tasks/{tasks}', [
    'uses' => '\teht\Http\Controllers\ProjectTasksController@deleteOneProjectTask',
]);

Route::post('projects/{projects}/files', [
     'uses' => '\teht\Http\Controllers\FilesController@uploadAttachments',
     'as'   => 'projects.files',
     'middleware' => ['auth']
]);

Route::post('projects/{projects}/comments', [
    'uses' => 'ProjectCommentsController@postNewComment',
    'as'   => 'projects.comments.create',
    'middleware' => ['auth']
]);

Route::get('projects/{projects}/comments/{comments}/edit', [
    'uses' => 'ProjectCommentsController@getOneProjectComment',
    'as' => 'projects.comments'
]);

Route::put('projects/{projects}/comments/{comments}', [
    'uses' => 'ProjectCommentsController@updateOneProjectComment',
]);

Route::delete('projects/{projects}/comments/{comments}', [
    'uses' => 'ProjectCommentsController@deleteOneProjectComment',
]);

Route::post('projects/{projects}/collaborators', [
    'uses' => 'ProjectCollaboratorsController@addCollaborator',
    'as'   => 'projects.collaborators.create',
    'middleware' => ['auth']
]);
*/


Route::get('/',['as' => 'home', 'uses' => 'ProjectsController@index']);

Route::get('/home',['as' => 'home', 'uses' => 'ProjectsController@index']);
Route::get('search', array(
     'as'    =>  'search',
     'uses'  =>  'SearchController@index'
 ));

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::group(['middleware' => ['auth']], function()
{
	Route::model('tasks', 'Task');
	Route::model('projects', 'Project');

	Route::bind('tasks', function($value, $route) {
	return teht\Task::whereSlug($value)->first();
	});
	Route::bind('projects', function($value, $route) {
	return teht\Project::whereSlug($value)->first();
	});

	Route::resource('projects', 'ProjectsController');
	Route::resource('projects.tasks', 'TasksController');
	Route::get('create','ProjectsController@create');
	// show new ticket form
	Route::get('new-ticket','PostController@create');
	//show all tickets
	Route::get('/tickets', 'PostController@index');

	// save new ticket
	Route::post('new-ticket','PostController@store');
	
	// edit ticket form
	Route::get('edit/{slug}','PostController@edit');
	
	// update ticket
	Route::post('update','PostController@update');
	
	// delete ticket
	Route::get('delete/{id}','PostController@destroy');
	
	// display user's all tickets
	Route::get('my-all-posts','UserController@user_posts_all');
	
	// display user's drafts
	Route::get('my-drafts','UserController@user_posts_draft');
	
	
	// add comment
	Route::post('comment/add','CommentController@store');
	
	// delete comment
	Route::post('comment/delete/{id}','CommentController@destroy');
	
});

//users profile
Route::get('user/{id}','UserController@profile')->where('id', '[0-9]+');

// display list of tickets
Route::get('user/{id}/posts','UserController@user_posts')->where('id', '[0-9]+');

// display single ticket
Route::get('/{slug}',['as' => 'post', 'uses' => 'PostController@show'])->where('slug', '[A-Za-z0-9-_]+');

PHP/Laravel/Projekti/app/Project.php
<?php namespace teht;

use Illuminate\Database\Eloquent\Model;

class Project extends Model {

    protected $guarded = [];

    public function tasks()
    {
        return $this->hasMany('teht\Task');
    }

}

PHP/Laravel/Projekti/app/Http/Controllers/ProjectsController.php
<?php namespace teht\Http\Controllers;

use Input;
use Redirect;
use teht\Project;
use Illuminate\Http\Request;
use teht\Http\Controllers\Controller;

class ProjectsController extends Controller {

	protected $rules = [
		'name' => ['required', 'min:3'],
		'slug' => ['required'],
	];

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$projects = Project::all();
		return view('projects.index', compact('projects'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('projects.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$this->validate($request, $this->rules);

		$input = Input::all();
		Project::create( $input );

		return Redirect::route('projects.index')->with('message', 'Project created');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  \teht\Project $project
	 * @return Response
	 */
	public function show(Project $project)
	{
		return view('projects.show', compact('project'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  \teht\Project $project
	 * @return Response
	 */
	public function edit(Project $project)
	{
		return view('projects.edit', compact('project'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \teht\Project $project
	 * @param \Illuminate\Http\Request $request
	 * @return Response
	 */
	public function update(Project $project, Request $request)
	{
		$this->validate($request, $this->rules);

		$input = array_except(Input::all(), '_method');
		$project->update($input);

		return Redirect::route('projects.show', $project->slug)->with('message', 'Project updated.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  \teht\Project $project
	 * @return Response
	 */
	public function destroy(Project $project)
	{
		$project->delete();

		return Redirect::route('projects.index')->with('message', 'Project deleted.');
	}

}

PHP/Laravel/Projekti/app/Http/Controllers/projekti 2/ProjectController.php
<?php
 
namespace teht\Http\Controllers;
use Auth;
use teht\Comment;
use teht\File;
use teht\Project;
use teht\Collaboration;
use Illuminate\Http\Request;
use teht\Task;
use teht\Http\Requests;
use teht\Http\Controllers\Controller;
 
class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
{
   $projects = Project::personal()->get();
   return view('projects.index')->withProject($projects);
}
 
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
     public function create()
 {
        return view('projects.new');
 }
 
    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
     public function store(Request $request)
    {
        $this->validate($request, [
            'name'     => 'required|min:3',
            'due-date' => 'required|date|after:today',
            'notes'    => 'required|min:10',
            'status'   => 'required'
        ]);
 
        $project = new Project;
        $project->project_name   = $request->input('name');
        $project->project_status = $request->input('status');
        $project->due_date       = $request->input('due-date');
        $project->project_notes  = $request->input('notes');
        $project->user_id        = Auth::user()->id;
 
        $project->save();
 
        return redirect()->route('projects.index')->with('info','Your Project has been created successfully');
    }
 
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
      public function show($id)
    {
        $project       = Project::find($id);
        $tasks         = $this->getTasks($id);
        $files         = $this->getFiles($id);
        $comments      = $this->getComments($id);
        $collaborators = $this->getCollaborators($id);
        return view('projects.show')
                            ->withProject($project)
                            ->withTasks($tasks)
                            ->withFiles($files)
                            ->withComments($comments)
                            ->withCollaborators($collaborators);
    }
 
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $project = Project::find($id);
  return view('projects.edit')->withProject($project);
    }
 
    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
         $project = Project::findOrFail($id);
        $this->validate($request, [
            'project_name'     => 'required|min:3',
            'due-date' => 'required|date|after:today',
            'project_notes'    => 'required|min:10',
            'project_status'   => 'required'
        ]);
 
        $values = $request->all();
        $project->fill($values)->save();
 
        return redirect()->back()->with('info','Your Project has been updated successfully');
    }
 
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
{
        $project = Project::findOrFail($id);
        $project->delete();
 
        return redirect()->route('projects.index')->with('info', 'Project deleted successfully');
}

public function getTasks($id)
    {
        $tasks =  Task::project($id)->get();
        return $tasks;
    }

public function getFiles($id)
    {
        $files =  File::project($id)->get();
        return $files;
    }

 public function getComments($id)
    {
        $comments = Comment::project($id)->get();
        return $comments;
    }

public function getCollaborators($id)
    {
        $collaborators = Collaboration::project($id)->get();
        return $collaborators;
    }


}

PHP/Laravel/Projekti/resources/views/projects/create.blade.php
@extends('app')
@section('title')
<h2>Create Project</h2>
@endSection
@section('content')
    

    {!! Form::model(new teht\Project, ['route' => ['projects.store']]) !!}
        @include('projects/partials/_form', ['submit_text' => 'Create Project'])
    {!! Form::close() !!}
@endsection

PHP/Laravel/Projekti/resources/views/projects/edit.blade.php
@extends('app')
@section('title')
<h2>Edit Project</h2>
@endSection
@section('content')
   

    {!! Form::model($project, ['method' => 'PATCH', 'route' => ['projects.update', $project->slug]]) !!}
        @include('projects/partials/_form', ['submit_text' => 'Edit Project'])
    {!! Form::close() !!}
@endsection

PHP/Laravel/Projekti/resources/views/projects/index.blade.php
@extends('app')
@section('title')
<h2>Projects</h2>
@endSection
@section('content')
    

    @if ( !$projects->count() )
        You have no projects
    @else
        <ul>
            @foreach( $projects as $project )
                <li>
                    {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('projects.destroy', $project->slug))) !!}
                        <a href="{{ route('projects.show', $project->slug) }}">{{ $project->name }}</a>
                        
                            {!! link_to_route('projects.edit', 'Edit', array($project->slug), array('class' => 'btn btn-info')) !!}
                            {!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}
                        
                    {!! Form::close() !!}
                </li>
            @endforeach
        </ul>
    @endif

    <p>
        {!! link_to_route('projects.create', 'Create Project') !!}
    </p>
@endsection

PHP/Laravel/Projekti/resources/views/projects/show.blade.php
@extends('app')

@section('title')
<h2>{{ $project->name }}</h2>
@endSection
@section('content')
    <h2>Tasks</h2>

    @if ( !$project->tasks->count() )
        Your project has no tasks.
    @else
        <ul>
            @foreach( $project->tasks as $task )
                <li>
                    {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('projects.tasks.destroy', $project->slug, $task->slug))) !!}
                        <a href="{{ route('projects.tasks.show', [$project->slug, $task->slug]) }}">{{ $task->name }}</a>
                        
                            {!! link_to_route('projects.tasks.edit', 'Edit', array($project->slug, $task->slug), array('class' => 'btn btn-info')) !!}

                            {!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}
                        
                    {!! Form::close() !!}
                </li>
            @endforeach
        </ul>
    @endif

    <p>
        {!! link_to_route('projects.index', 'Back to Projects') !!} |
        {!! link_to_route('projects.tasks.create', 'Create Task', $project->slug) !!}
    </p>
@endsection